p{
	font-size:20px;
}
a{
	direction:rtl;
	text-align:right;
}
ul{
	font-size:20px;
}
footer{
 background-color:#f2f2f2;
 padding:10px;
 font-family:tahoma;
 font-size:14px;
}
 .navbar {background: #797979;direction: rtl;text-align: right;padding-right: 30px;}
  ul.menu li { display: inline-block;list-style: none; }
  ul.menu li a { display:inline-block;padding: 12px;color: #fff;text-decoration: none; }
  	
ul.submenu { display: none; }
body {
     background-color:gray;
}
